//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSpammer.resx {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class SmartSpammerSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static SmartSpammerSettings defaultInstance = ((SmartSpammerSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SmartSpammerSettings())));
        
        public static SmartSpammerSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("500, 300, 700, 350")]
        public global::System.Drawing.Rectangle BOUNDS {
            get {
                return ((global::System.Drawing.Rectangle)(this["BOUNDS"]));
            }
            set {
                this["BOUNDS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string DOS_IP {
            get {
                return ((string)(this["DOS_IP"]));
            }
            set {
                this["DOS_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9900")]
        public int DOS_PORT {
            get {
                return ((int)(this["DOS_PORT"]));
            }
            set {
                this["DOS_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("localhost")]
        public string FFS_IP {
            get {
                return ((string)(this["FFS_IP"]));
            }
            set {
                this["FFS_IP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9910")]
        public int FFS_PORT {
            get {
                return ((int)(this["FFS_PORT"]));
            }
            set {
                this["FFS_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int THREADS {
            get {
                return ((int)(this["THREADS"]));
            }
            set {
                this["THREADS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int EXECUTIONS {
            get {
                return ((int)(this["EXECUTIONS"]));
            }
            set {
                this["EXECUTIONS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int RULE_GENERATION_NUMBER_OF_OUTCOMES {
            get {
                return ((int)(this["RULE_GENERATION_NUMBER_OF_OUTCOMES"]));
            }
            set {
                this["RULE_GENERATION_NUMBER_OF_OUTCOMES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int RULE_GENERATION_NUMBER_OF_NEIGHBOURS_ON_EACH_SIDE {
            get {
                return ((int)(this["RULE_GENERATION_NUMBER_OF_NEIGHBOURS_ON_EACH_SIDE"]));
            }
            set {
                this["RULE_GENERATION_NUMBER_OF_NEIGHBOURS_ON_EACH_SIDE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int RULE_GENERATION_RULE_ACTIVATION_ALGORITHM {
            get {
                return ((int)(this["RULE_GENERATION_RULE_ACTIVATION_ALGORITHM"]));
            }
            set {
                this["RULE_GENERATION_RULE_ACTIVATION_ALGORITHM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int RULE_GENERATION_DECISION_ACTIVATION_ALGORITHM {
            get {
                return ((int)(this["RULE_GENERATION_DECISION_ACTIVATION_ALGORITHM"]));
            }
            set {
                this["RULE_GENERATION_DECISION_ACTIVATION_ALGORITHM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int INFERENCE_ALGORITHM {
            get {
                return ((int)(this["INFERENCE_ALGORITHM"]));
            }
            set {
                this["INFERENCE_ALGORITHM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double IMPORTANCE_A {
            get {
                return ((double)(this["IMPORTANCE_A"]));
            }
            set {
                this["IMPORTANCE_A"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double IMPORTANCE_B {
            get {
                return ((double)(this["IMPORTANCE_B"]));
            }
            set {
                this["IMPORTANCE_B"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double IMPORTANCE_C {
            get {
                return ((double)(this["IMPORTANCE_C"]));
            }
            set {
                this["IMPORTANCE_C"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int IMPORTANCE_FUNCTION {
            get {
                return ((int)(this["IMPORTANCE_FUNCTION"]));
            }
            set {
                this["IMPORTANCE_FUNCTION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RULE_GENERATION_FORCE_NEIGHBOURS {
            get {
                return ((bool)(this["RULE_GENERATION_FORCE_NEIGHBOURS"]));
            }
            set {
                this["RULE_GENERATION_FORCE_NEIGHBOURS"] = value;
            }
        }
    }
}
