//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartSpammer.resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SmartSpammerStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SmartSpammerStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartSpammer.resx.SmartSpammerStrings", typeof(SmartSpammerStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error trying to save the file !
        ///Please make sure the file isn&apos;t opened by another program and that you have access to modify it..
        /// </summary>
        internal static string ERROR_FILE_SAVING {
            get {
                return ResourceManager.GetString("ERROR_FILE_SAVING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Domain Ontology Service didn&apos;t respond.
        ///Please check that it is running and that you have the correct address and port set..
        /// </summary>
        internal static string ERROR_NO_RESPONSE_DOS {
            get {
                return ResourceManager.GetString("ERROR_NO_RESPONSE_DOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Functionality Finding Service didn&apos;t respond.
        ///Please check that it is running and that you have the correct address and port set..
        /// </summary>
        internal static string ERROR_NO_RESPONSE_FFS {
            get {
                return ResourceManager.GetString("ERROR_NO_RESPONSE_FFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Far *.
        /// </summary>
        internal static string FAR {
            get {
                return ResourceManager.GetString("FAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Near *.
        /// </summary>
        internal static string NEAR {
            get {
                return ResourceManager.GetString("NEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quite close *.
        /// </summary>
        internal static string QUITE_CLOSE {
            get {
                return ResourceManager.GetString("QUITE_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quite far *.
        /// </summary>
        internal static string QUITE_FAR {
            get {
                return ResourceManager.GetString("QUITE_FAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strong *.
        /// </summary>
        internal static string STRONG {
            get {
                return ResourceManager.GetString("STRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very close *.
        /// </summary>
        internal static string VERY_CLOSE {
            get {
                return ResourceManager.GetString("VERY_CLOSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very far *.
        /// </summary>
        internal static string VERY_FAR {
            get {
                return ResourceManager.GetString("VERY_FAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Strong *.
        /// </summary>
        internal static string VERY_STRONG {
            get {
                return ResourceManager.GetString("VERY_STRONG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Very Weak *.
        /// </summary>
        internal static string VERY_WEAK {
            get {
                return ResourceManager.GetString("VERY_WEAK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weak *.
        /// </summary>
        internal static string WEAK {
            get {
                return ResourceManager.GetString("WEAK", resourceCulture);
            }
        }
    }
}
