//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3074
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DomainOntologyService.resx {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class DomainOntologyServiceSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static DomainOntologyServiceSettings defaultInstance = ((DomainOntologyServiceSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DomainOntologyServiceSettings())));
        
        public static DomainOntologyServiceSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200, 200, 291, 483")]
        public global::System.Drawing.Rectangle BOUNDS {
            get {
                return ((global::System.Drawing.Rectangle)(this["BOUNDS"]));
            }
            set {
                this["BOUNDS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("113")]
        public int SEPARATOR_FUNCTIONALITIES_PROPERTIES {
            get {
                return ((int)(this["SEPARATOR_FUNCTIONALITIES_PROPERTIES"]));
            }
            set {
                this["SEPARATOR_FUNCTIONALITIES_PROPERTIES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("113")]
        public int SEPARATOR_PROPERTIES_TERMS {
            get {
                return ((int)(this["SEPARATOR_PROPERTIES_TERMS"]));
            }
            set {
                this["SEPARATOR_PROPERTIES_TERMS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9900")]
        public int LISTENING_PORT {
            get {
                return ((int)(this["LISTENING_PORT"]));
            }
            set {
                this["LISTENING_PORT"] = value;
            }
        }
    }
}
