//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FunctionalityFindingService.resx {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FunctionalityFindingServiceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FunctionalityFindingServiceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FunctionalityFindingService.resx.FunctionalityFindingServiceStrings", typeof(FunctionalityFindingServiceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request couldn&apos;t be handled because when the Functionality Finding Service tryed to connect to the Domain Ontology Service, the following error occured:.
        /// </summary>
        internal static string ERROR_DOS_ERROR {
            get {
                return ResourceManager.GetString("ERROR_DOS_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request couldn&apos;t be handled because the Functionality Finding Service couldn&apos;t connect to the Domain Ontology Service.
        ///Please check that both services are running and configured accordingly..
        /// </summary>
        internal static string ERROR_DOS_NO_RESPONSE {
            get {
                return ResourceManager.GetString("ERROR_DOS_NO_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Domain Ontology Service didn&apos;t respond.
        ///Please check that it is running and that you have the correct address and port set..
        /// </summary>
        internal static string ERROR_NO_RESPONSE {
            get {
                return ResourceManager.GetString("ERROR_NO_RESPONSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There aren&apos;t any services providing the requested functionality in the database..
        /// </summary>
        internal static string ERROR_NO_SERVICES_IN_DB {
            get {
                return ResourceManager.GetString("ERROR_NO_SERVICES_IN_DB", resourceCulture);
            }
        }
    }
}
